language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t dockintocloud/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dockintocloud/docker-react npm run test -- --coverage